### PR TITLE
Encapsulation and Abstraction

### PR DESCRIPTION
**Pull request by BalajiSriraman**

### CODE REVIEW

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/58b954b5f4524fda98dc211e28cf47d8?sid=1b60e2ff-0dd1-45a0-a9ed-d57c9bc250d7

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/b8294024b52d45d09211fced20b8bc43?sid=195c6a53-30c6-4e13-ac34-3e9ba0bae54d

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/6a09e3cbf52e428081db41819ef235d3?sid=262d6583-4f8c-4206-8443-b723826b132b

**Comment by BalajiSriraman** [comment]
Output:

https://www.loom.com/share/b0c1e71f70754ec1a7ec1948ad783ea4?sid=828373b8-27bd-4947-9777-ed88c94d24c2

**Comment by Tharun-kailash** [comment]
I have reviewed the video and code, Balaji.
The self viva is clear and you have explained the concepts clearly.
Please merge this PR!
Thanks.

**Pull request merged**
