### PR TITLE
Abstract class

### PR DESCRIPTION
**Pull request by BalajiSriraman**

### CODE REVIEW

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/d9c7afcd0e244ca4afd50841241919f3?sid=ce3368f7-2789-4f09-b482-82a2a606c79a

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/8f9682e012294263a215e6e3b3a9982a?sid=c28d8797-e37e-497e-83a4-0e87f407c34c

**Comment by BalajiSriraman** [comment]
currently the output of the code is no different functionally i have just changed the style of coding

i have also implemented some new routes which will be made functional in upcoming PRs

**Comment by Tharun-kailash** [comment]
Hey Balaji,
Review is done.
Pl merge this PR!

**Pull request merged**
