### PR TITLE
Milestone-1

### PR DESCRIPTION
**Pull request by BalajiSriraman**
The Below PR demonstrate's the following OOPs concepts

- Classes and Objects
- Constructors and Destructors

### CODE REVIEW

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/48c09575e8e44fbbaef90fce508d8b4a?sid=c37dc27a-f3a8-4828-a1a4-1f77aa1d52fd

**Comment by BalajiSriraman** [comment]
<div style="position: relative; padding-bottom: 54.166666666666664%; height: 0;"><iframe src="https://www.loom.com/embed/48c09575e8e44fbbaef90fce508d8b4a?sid=b1d966ae-20b0-4d6a-9f6e-70e63b0be4a7" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe></div>

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/6c7742f8be3b4801b2e2e5dbbe98778c?sid=af6ac8dc-d9be-4e7e-95ca-6f67d8548039

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/a2ffaf430f0547efb20521b9a679f1f4?sid=224dab26-e9f7-4ca0-8a3a-0124cb479464

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/23219838b9324c638af668805401b3c6?sid=c6d35c5f-a4e3-4c21-835c-8f6595127e93

**Comment by Tharun-kailash** [comment]
Thanks for submitting, Balaji.
However variable naming conventions can be better. Let's say you have specified name, email which is not clear who this belongs to. There will be people who are posting the blogs and reading the blogs. Try adopting a new convention.

The way you explained your code is really good. But you have to update the videos during different PRs not in the same one. You have to raise individual PRs for all the 13 concepts mentioned in the wiki doc. Pl look into it.
For now, I will be evaluating the usage of classes and objects only. Remaining raise separate PRs.

You can go ahead and merge this PR!
Thanks.

**Comment by BalajiSriraman** [comment]
Thx for the feedback @Tharun-kailash!
Just to let you know since its the 1st milestone I didn't keep naming as priority but will have a proper convention later in upcoming PR's

**Pull request merged**
