### PR TITLE
Inheritance

### PR DESCRIPTION
**Pull request by BalajiSriraman**

### CODE REVIEW

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/249db20c961541aca8cd9676040598c3?sid=aa11e186-f873-44eb-8767-e5050883997f

**Comment by BalajiSriraman** [comment]
https://www.loom.com/share/b11d099a7e934f26b57ed4003b54898b?sid=d98ad9fb-db1e-4396-93e3-d80f197bd2fb

**Comment by BalajiSriraman** [comment]
theres no change in output it still the same

**Comment by Tharun-kailash** [comment]
Your self viva is good, Balaji.
Pl go ahead and merge this PR!

**Pull request merged**
